version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123!@#
    ports:
      - "15672:15672"
      - "5672:5672"