server:
  port : 8081

logging:
  level:
    org:
      springframework:
        security=DEBUG:

spring:
  application:
    name : store-admin
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.hbm2ddl.auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
